[package]
name = "tokio-timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25", features = ["time","sync","rt-multi-thread","macros"] }
once_cell = "1.17"